services:
  olimp:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pg
      POSTGRES_USER: ps
      POSTGRES_DB: pg
    ports:
      - 5432:5432
    volumes:
      - olimp_bd_data:/var/lib/postgresql/data

volumes:
  olimp_bd_data:
