services:
  olimp:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - olimp_bd_data:/var/lib/postgresql/data

volumes:
  olimp_bd_data:
