version: "3.9"

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle_database
    restart: always
    environment:
      ORACLE_PWD: hack_me
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - db_data:/opt/oracle/oradata

volumes:
  db_data:
    driver: local
