version: "3"
services:
  postgres-1:
    image: postgres:alpine
    container_name: pg-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hack_me
      POSTGRES_DB: db-1
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres-2:
    image: postgres:alpine
    container_name: pg-2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hack_me
      POSTGRES_DB: db-2
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata1:
  pgdata2:
